In [2]:
import numpy as np

In [1]:
# Load Data
import pandas as pd

df = pd.read_csv("C:/Users/mayan/OneDrive/Desktop/Mayank(HP)/programs/Learning_AIML/Cleaned_data/powerplant_data.csv")

In [3]:
df.head()
# AT = Temperatuer
# V = vaccum
# AP = pressure
# RH = humidity

# PE = Produced Energy

      AT      V       AP     RH      PE
0   8.34  40.77  1010.84  90.01  480.48
1  23.64  58.49  1011.40  74.20  445.75
2  29.74  56.90  1007.15  41.91  438.76
3  19.07  49.69  1007.22  76.79  453.09
4  11.80  40.66  1017.13  97.20  464.43

In [4]:
df.isnull().sum()

AT    0
V     0
AP    0
RH    0
PE    0
dtype: int64

In [19]:
X = df.drop("PE",axis = 1)
y = df["PE"]

In [20]:
X.head()

      AT      V       AP     RH
0   8.34  40.77  1010.84  90.01
1  23.64  58.49  1011.40  74.20
2  29.74  56.90  1007.15  41.91
3  19.07  49.69  1007.22  76.79
4  11.80  40.66  1017.13  97.20

In [22]:
# Split out Data
from sklearn.model_selection import train_test_split

X_train , X_test , y_train, y_test = train_test_split(
    X , y,test_size= 0.2 , random_state = 42
)

In [23]:
df.shape

(9568, 5)

In [24]:
from sklearn.preprocessing import StandardScaler 

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_train)

In [25]:
X_train_scaled

array([[ 0.74805289,  0.72006931, -0.32660017, -0.49711722],
       [ 0.86181948,  1.26515721, -0.98521113,  0.8181501 ],
       [ 0.93409473,  1.52314975,  0.32523844,  0.80167494],
       ...,
       [-0.22097078, -0.834965  ,  0.36756563, -0.83554456],
       [ 0.94747903,  1.14245344, -0.41971997, -0.45455637],
       [-1.77355014, -1.19049131,  1.92520594,  0.91837402]])

In [26]:
import torch 
import torch.nn as nn

In [29]:
# Convert data into tensors 

X_train_tensor = torch.tensor(X_train_scaled , dtype = torch.float32)
X_test_tensor = torch.tensor(X_test_scaled , dtype = torch.float32)

y_train_tensor = torch.tensor(y_train.values , dtype = torch.float32).view(-1 ,1)
y_test_tensor = torch.tensor(y_test.values , dtype = torch.float32).view(-1 ,1)

# .values is written because y_train is not a numpy array 
# .view = we are changing the dimensions of y_tain by this ,[1,2,3,..] =>[[1],[2],[3]..]